FROM node:22.9.0-alpine as builder

WORKDIR /app

ARG KIBANA_DASHBOARD_URL
ARG PAYMENT_INGESTION_URL
ARG PAYMENT_WEBSOCKET_NOTIFICATION

ENV NEXT_PUBLIC_KIBANA_DASHBOARD_URL=$KIBANA_DASHBOARD_URL
ENV NEXT_PUBLIC_PAYMENT_INGESTION_URL=$PAYMENT_INGESTION_URL
ENV NEXT_PUBLIC_PAYMENT_WEBSOCKET_NOTIFICATION=$PAYMENT_WEBSOCKET_NOTIFICATION

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:22.9.0-alpine AS runner
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/package.json ./package.json

EXPOSE 3000

CMD ["npm", "start"]
