name: Trigger auto deployment for payment-processing

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  #push:
  #  branches:
  #    [ main ]
  #  paths:
  #  - '**'
  #  - '.github/workflows/payment-processing-AutoDeployTrigger-3b0cfc2b-a1c1-4172-a225-e6d64b45b9dc.yml'

  # Allow manual trigger 
  workflow_dispatch:      

env:
  AZURE_CONTAINER_REGISTRY: paymentprocessing
  CONTAINER_APP_NAME: payment-processing
  RESOURCE_GROUP: sideprojects

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SIDEPROJECTS_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}payment-ingestion/src
          acrName: ${{ env.AZURE_CONTAINER_REGISTRY }}
          dockerfilePath: payment-processing/Dockerfile_processing
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          buildArguments: |
            KAFKA_BOOTSTRAP_SERVERS=${{ secrets.KAFKA_BOOTSTRAP_SERVERS }}
            KAFKA_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username='${{ secrets.KAFKA_USERNAME }}' password='${{ secrets.KAFKA_PASSWORD }}';
            CASSANDRA_CONTACT_POINTS=${{ secrets.CASSANDRA_CONTACT_POINTS }}
            CASSANDRA_KEYSPACE_NAME=${{ secrets.CASSANDRA_KEYSPACE_NAME }}
            CASSANDRA_PORT=${{ secrets.CASSANDRA_PORT }}
            CASSANDRA_USERNAME=${{ secrets.CASSANDRA_USERNAME }}
            CASSANDRA_PASSWORD=${{ secrets.CASSANDRA_PASSWORD }}
            CASSANDRA_LOCAL_DATACENTER=${{ secrets.CASSANDRA_LOCAL_DATACENTER }}
            RABBITMQ_HOST=${{ secrets.RABBITMQ_HOST }}
            RABBITMQ_PORT=${{ secrets.RABBITMQ_PORT }}
            RABBITMQ_USERNAME=${{ secrets.RABBITMQ_USERNAME }}
            RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }}
            
            
            
