name: Trigger auto deployment for pruebaingestion

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/pruebaingestion-AutoDeployTrigger-eeee1cbc-8c25-4fc9-ad57-52f19629d328.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PRUEBAINGESTION_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PRUEBAINGESTION_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PRUEBAINGESTION_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.PRUEBAINGESTION_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PRUEBAINGESTION_REGISTRY_PASSWORD }}
          containerAppName: pruebaingestion
          resourceGroup: sideprojects
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


